services:
  s3cmd:
    image: 'alpine:latest'
    entrypoint: |
      /bin/sh -c " apk upgrade --no-cache; apk add --no-cache ca-certificates s3cmd coreutils; tail -f /dev/null "
    volumes:
      - './tools:/data/tools'
      - 's3cmd-data:/data/backups'
    env_file: ".env"

volumes:
  s3cmd-data: